---
- name: Delete | import common tasks
  tags:
    - horizon
    - openstack
  ansible.builtin.import_tasks: "common.yml"

- name: Delete | purge packages
  tags:
    - horizon
    - openstack
  ansible.builtin.apt:
    name: "{{ item }}"
    purge: true
    state: absent
  loop: "{{ packages }}"
  become: true
...
